ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
minimumReleaseAge: 10080 # 7 days
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.0
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.2.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
