repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [html, svg]
        exclude: "frontend/app/client/.*|frontend/components\\.json|backend/alembic/README"
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents", "--unsafe"]
      - id: check-json
        exclude: "\\.vscode/launch\\.json"
      - id: check-added-large-files
        args: ["--enforce-all"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.14
    hooks:
      - id: uv-lock
        files: backend/pyproject.toml
        args: [--project, backend]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
