# name: scholark
services:
  db:
    image: postgres:17.4
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SCHOLARK_POSTGRES_USER} -d ${SCHOLARK_POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - scholark-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${SCHOLARK_POSTGRES_PORT?Variable not set}:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${SCHOLARK_POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${SCHOLARK_POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${SCHOLARK_POSTGRES_DB?Variable not set}

  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${SCHOLARK_BACKEND_PORT?Variable not set}:8000"
    environment:
      - SCHOLARK_FRONTEND_HOST=${SCHOLARK_FRONTEND_HOST?Variable not set}
      - SCHOLARK_BACKEND_CORS_ORIGINS=${SCHOLARK_BACKEND_CORS_ORIGINS?Variable not set}
      - SCHOLARK_POSTGRES_SERVER=db
      - SCHOLARK_POSTGRES_PORT=5432
      - SCHOLARK_POSTGRES_USER=${SCHOLARK_POSTGRES_USER?Variable not set}
      - SCHOLARK_POSTGRES_PASSWORD=${SCHOLARK_POSTGRES_PASSWORD?Variable not set}
      - SCHOLARK_POSTGRES_DB=${SCHOLARK_POSTGRES_DB?Variable not set}
      - SCHOLARK_FIRST_SUPERUSER=${SCHOLARK_FIRST_SUPERUSER?Variable not set}
      - SCHOLARK_FIRST_SUPERUSER_PASSWORD=${SCHOLARK_FIRST_SUPERUSER_PASSWORD?Variable not set}

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${SCHOLARK_FRONTEND_PORT?Variable not set}:3000"
    environment:
      - VITE_API_URL=backend:8000


volumes:
  scholark-db-data:
    # name: scholark_db-data
