"""add created_at and updated_at columns to conference table

Revision ID: 82c075962f45
Revises: 7f4e52752aba
Create Date: 2025-04-24 00:10:14.578088+00:00

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82c075962f45"
down_revision: str | None = "7f4e52752aba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.now(UTC)
    op.add_column("conference", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=f"'{now}'"))
    op.add_column("conference", sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=f"'{now}'"))
    op.alter_column("conference", "created_at", server_default=None)  # type: ignore[arg-type]
    op.alter_column("conference", "updated_at", server_default=None)  # type: ignore[arg-type]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conference", "updated_at")
    op.drop_column("conference", "created_at")
    # ### end Alembic commands ###
