"""Add conference subscriptions and slack_user_id

Revision ID: f510e294b98a
Revises: 5de4313fd490
Create Date: 2026-04-12 21:58:56.925485+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f510e294b98a"
down_revision: str | None = "5de4313fd490"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conferencesubscription",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conference_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conference_id"], ["conference.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "conference_id"),
    )
    op.add_column("user", sa.Column("slack_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "slack_user_id")
    op.drop_table("conferencesubscription")
    # ### end Alembic commands ###
