// This file is auto-generated by @hey-api/openapi-ts

export type ConferenceCreate = {
    name: string;
    start_date?: string | null;
    end_date?: string | null;
    location?: string | null;
    website_url?: string | null;
    abstract_deadline?: string | null;
    paper_deadline?: string | null;
};

export type ConferencePublic = {
    name: string;
    start_date?: string | null;
    end_date?: string | null;
    location?: string | null;
    website_url?: string | null;
    abstract_deadline?: string | null;
    paper_deadline?: string | null;
    id: string;
};

export type ConferencesPublic = {
    data: Array<ConferencePublic>;
    count: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ConferencesReadConferencesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/conferences/';
};

export type ConferencesReadConferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConferencesReadConferencesError = ConferencesReadConferencesErrors[keyof ConferencesReadConferencesErrors];

export type ConferencesReadConferencesResponses = {
    /**
     * Successful Response
     */
    200: ConferencesPublic;
};

export type ConferencesReadConferencesResponse = ConferencesReadConferencesResponses[keyof ConferencesReadConferencesResponses];

export type ConferencesCreateConferenceData = {
    body: ConferenceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/conferences/';
};

export type ConferencesCreateConferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConferencesCreateConferenceError = ConferencesCreateConferenceErrors[keyof ConferencesCreateConferenceErrors];

export type ConferencesCreateConferenceResponses = {
    /**
     * Successful Response
     */
    200: ConferencePublic;
};

export type ConferencesCreateConferenceResponse = ConferencesCreateConferenceResponses[keyof ConferencesCreateConferenceResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
