name: Build Docker Images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose Build
        run: |
          docker compose build

  collect-docker-build:
    needs: [docker-compose-build]
    runs-on: ubuntu-latest
    steps:
      - name: Collect results
        run: echo "Docker images built successfully."
