name: Lint Python
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UV_VERSION: "0.8.x"
  UV_FROZEN: "1"
  UV_NO_SYNC: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install Ruff
        run: uv sync --only-group ruff

      - name: Run Ruff
        run: uv run -- ruff check

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install the project
        run: uv sync --no-dev --group typing

      - name: Run mypy
        run: uv run -- mypy .

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install the project
        run: uv sync --no-dev --group typing

      - name: Run mypy
        run: uv run -- pyright .

  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install the project
        run: uv sync --no-dev --group typing

      - name: Run mypy
        run: uv run -- ty check

  pyrefly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install the project
        run: uv sync --no-dev --group typing

      - name: Run mypy
        run: uv run -- pyrefly check

  collect-lint-python:
    needs: [ruff, mypy, pyright, ty, pyrefly]
    runs-on: ubuntu-latest
    steps:
      - name: Collect results
        run: echo "All checks passed!"
        working-directory: .
