name: Lint Python
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UV_VERSION: "0.7.x"
  UV_FROZEN: "1"
  UV_NO_SYNC: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./backend

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Ruff
        run: uv sync --only-group ruff

      - name: Run Ruff
        run: uv run -- ruff check
